import "bootstrap/dist/css/bootstrap.min.css";
import "aos/dist/aos.css";
import { Sora } from "next/font/google";
import { PortfolioContentProvider } from "./context/PortfolioContentContext";
import SiteChrome from "./component/SiteChrome";

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Ashis's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <PortfolioContentProvider>
          <SiteChrome>{children}</SiteChrome>
        </PortfolioContentProvider>
      </body>
    </html>
  );
}
